name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v6
        with:
          repository: "frappe/backport"
          path: ./actions
          ref: develop
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run backport
        if: ${{ env.RELEASE_TOKEN != '' }}
        uses: ./actions/backport
        with:
          token: ${{ env.RELEASE_TOKEN }}
          labelsToAdd: "backport"
          title: "{{originalTitle}}"
